### ISSUE TITLE
InitializeSettings command line arg override not correct for some settings

### ISSUE THREAD

**Issue by numgithub** [jamesnovak/PortalRecordsMoverConsole#1]
Hi - I just noticed the following:
                    case "user":
                        settings.Config.SourceEnvironment = arg.Value;
                        break;
                    case "pass":
                        settings.Config.SourceEnvironment = arg.Value;

I guess the intention is the following instead:
                    case "user":
                        settings.Config.Username = arg.Value;
                        break;
                    case "pass":
                        settings.Config.Password = arg.Value;

Cheers,
Tim

**Comment by lbang** [comment]
Changing to this has also worked for me.

**Comment by jamesnovak** [comment]
thanks!  This should be fixed with the latest release.  Apologies for the delay!
