### ISSUE TITLE
Issue with Web Pages not being deployed

### ISSUE THREAD

**Issue by thesunchaser** [jamesnovak/PortalRecordsMoverConsole#3]
All of our custom web pages are not getting deployed through the console app.

Getting an error through the console app:

An error occured attempting the insert/update/associate: SelfAssessment (Web Page/c9bda040-71c8-e811-a8eb-00155d698609): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.

Could the console app be using an old version of the xrmtoolbox one?

**Comment by jamesnovak** [comment]
This should be fixed with the latest release.  Apologies for the delay!
